# Uncomment the next line to define a global platform for your project
 # platform :ios, '9.0'

target 'Messenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger

pod 'Firebase', '~> 10.11' 

pod 'FirebaseCore', '~> 10.11'

pod 'FirebaseAuth', '~> 10.11'

pod 'FirebaseFirestore', '~> 10.11'

pod 'FirebaseStorage', '~> 10.11'

pod 'FirebaseAnalytics', '~> 10.11'

pod 'FirebaseMessaging', '~> 10.11'

pod 'FirebaseFirestoreSwift', '~> 10.11'

pod 'RealmSwift'

pod 'ProgressHUD', '~> 13.6'

pod 'Gallery'

pod 'MessageKit'

pod 'InputBarAccessoryView'

pod 'YPImagePicker'

pod 'SKPhotoBrowser'

end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end









